// ---------------------------------------------------------------------------
// Auto-Compact -- Summarize old conversation messages to stay within limits
// ---------------------------------------------------------------------------
//
// When the conversation gets too long, this module replaces old messages
// with a summary system message while preserving the most recent messages
// verbatim.  The summary is generated by the /api/summarize-chat endpoint.
// ---------------------------------------------------------------------------

import { PRESERVE_RECENT } from './token-estimator';

export interface CompactableMessage {
  role: string;
  content: string;
}

/**
 * Request a summary of old messages from the API.
 *
 * @param oldMessages - Messages to summarize (the ones being replaced).
 * @returns A summary string, or a fallback if the API call fails.
 */
export async function summarizeOldMessages(
  oldMessages: CompactableMessage[],
): Promise<string> {
  try {
    const response = await fetch('/api/summarize-chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        messages: oldMessages.map((m) => ({
          role: m.role,
          content: m.content,
        })),
        purpose: 'compact',
      }),
    });

    if (response.ok) {
      const data = await response.json();
      return data.summary ?? 'Previous conversation context was summarized.';
    }
  } catch {
    // Fallback silently.
  }

  return 'Previous conversation context was summarized due to length.';
}

/**
 * Build a compacted message history.
 *
 * Replaces all messages before the preserved tail with a single system
 * message containing the AI-generated summary.
 *
 * @param messages - Full message history.
 * @param summary - The summary of old messages.
 * @returns A new array with the summary system message + recent messages.
 */
export function buildCompactedHistory(
  messages: CompactableMessage[],
  summary: string,
): CompactableMessage[] {
  if (messages.length <= PRESERVE_RECENT) {
    return messages;
  }

  const recentMessages = messages.slice(-PRESERVE_RECENT);

  const summaryMessage: CompactableMessage = {
    role: 'system',
    content: `[Context Summary] The following is a summary of the earlier conversation that was compacted to save context space:\n\n${summary}\n\n---\nThe conversation continues below with the most recent messages preserved.`,
  };

  return [summaryMessage, ...recentMessages];
}
