// ---------------------------------------------------------------------------
// TRIPOD Reference Data (GENERATED — do not edit manually)
// ---------------------------------------------------------------------------
//
// Generated by: scripts/build-tripod-data.ts
// Source: TRIPOD dataset (143 annotated records across 99 films)
//
// Run `npx tsx scripts/build-tripod-data.ts` to regenerate.
// ---------------------------------------------------------------------------

import type {
  TurningPointNorm,
  TurningPointKey,
  TripodMovieExample,
} from './types';

// ---------------------------------------------------------------------------
// Turning Point Position Norms
// ---------------------------------------------------------------------------

export const TURNING_POINT_NORMS: Record<TurningPointKey, TurningPointNorm> = {
  "tp1": {
    "name": "Opportunity",
    "aliases": [
      "Inciting Incident",
      "Catalyst"
    ],
    "savetheCatBeat": "Catalyst",
    "position": {
      "mean": 0.134,
      "median": 0.115,
      "p10": 0.039,
      "p25": 0.075,
      "p75": 0.169,
      "p90": 0.275
    },
    "pageGuide": {
      "median": 14,
      "typicalRange": [
        9,
        20
      ]
    },
    "description": "The event that disrupts the status quo and sets the story in motion."
  },
  "tp2": {
    "name": "Change of Plans",
    "aliases": [
      "End of Act 1",
      "Break into Two"
    ],
    "savetheCatBeat": "Break into Two",
    "position": {
      "mean": 0.311,
      "median": 0.303,
      "p10": 0.179,
      "p25": 0.208,
      "p75": 0.382,
      "p90": 0.472
    },
    "pageGuide": {
      "median": 36,
      "typicalRange": [
        25,
        46
      ]
    },
    "description": "The protagonist commits to a new direction. Act 2 begins."
  },
  "tp3": {
    "name": "Point of No Return",
    "aliases": [
      "Midpoint",
      "Midpoint Reversal"
    ],
    "savetheCatBeat": "Midpoint",
    "position": {
      "mean": 0.517,
      "median": 0.529,
      "p10": 0.379,
      "p25": 0.449,
      "p75": 0.583,
      "p90": 0.644
    },
    "pageGuide": {
      "median": 63,
      "typicalRange": [
        54,
        70
      ]
    },
    "description": "A false victory or defeat that raises stakes and changes the game."
  },
  "tp4": {
    "name": "Major Setback",
    "aliases": [
      "End of Act 2",
      "All Is Lost",
      "Break into Three"
    ],
    "savetheCatBeat": "Break into Three",
    "position": {
      "mean": 0.727,
      "median": 0.744,
      "p10": 0.613,
      "p25": 0.679,
      "p75": 0.794,
      "p90": 0.825
    },
    "pageGuide": {
      "median": 89,
      "typicalRange": [
        81,
        95
      ]
    },
    "description": "The lowest point where everything seems lost. New inspiration emerges."
  },
  "tp5": {
    "name": "Climax",
    "aliases": [
      "Final Confrontation",
      "Finale"
    ],
    "savetheCatBeat": "Finale",
    "position": {
      "mean": 0.882,
      "median": 0.892,
      "p10": 0.792,
      "p25": 0.848,
      "p75": 0.932,
      "p90": 0.95
    },
    "pageGuide": {
      "median": 107,
      "typicalRange": [
        102,
        112
      ]
    },
    "description": "The protagonist faces the final challenge, applying lessons learned."
  }
} as Record<TurningPointKey, TurningPointNorm>;

// ---------------------------------------------------------------------------
// Reference Film Examples
// ---------------------------------------------------------------------------

export const TRIPOD_EXAMPLES: TripodMovieExample[] = [
  {
    "movie": "Die Hard",
    "totalSentences": 44,
    "turningPoints": {
      "tp1": {
        "index": 2,
        "pct": 0.045,
        "text": "McClane is driven to the Nakatomi Plaza building for a company Christmas party by Argyle."
      },
      "tp2": {
        "index": 6,
        "pct": 0.136,
        "text": "Away from the other hostages, Gruber interrogates Takagi for the code to the building's vault as McClane secretly observes."
      },
      "tp3": {
        "index": 19,
        "pct": 0.432,
        "text": "Holly's coworker Harry Ellis attempts to mediate between Hans and McClane for the return of the detonators."
      },
      "tp4": {
        "index": 34,
        "pct": 0.773,
        "text": "Theo goes to the parking garage to retrieve their getaway vehicle but is knocked unconscious by Argyle who had been trapped in the garage during the siege."
      },
      "tp5": {
        "index": 40,
        "pct": 0.909,
        "text": "McClane and Holly are escorted from the building and meet Powell in person."
      }
    }
  },
  {
    "movie": "The Silence of the Lambs (film)",
    "totalSentences": 28,
    "turningPoints": {
      "tp1": {
        "index": 3,
        "pct": 0.107,
        "text": "Starling travels to the Baltimore State Hospital for the Criminally Insane, where she is led by Frederick Chilton to Lecter's solitary quarters."
      },
      "tp2": {
        "index": 10,
        "pct": 0.357,
        "text": "When Buffalo Bill kidnaps a US Senator's daughter, Catherine Martin, Crawford authorizes Starling to offer Lecter a fake deal promising a prison transfer if he provides information that helps find Buffalo Bill and rescue the abductee."
      },
      "tp3": {
        "index": 14,
        "pct": 0.5,
        "text": "As the manhunt begins, Starling visits Lecter at his special cell in a Tennessee courthouse and confronts him with her decryption of the name he provided (\"Louis Friend\", an anagram of \"iron sulfide\", also known as fool's gold)."
      },
      "tp4": {
        "index": 17,
        "pct": 0.607,
        "text": "Lecter gives her back the case files on Buffalo Bill after their conversation is interrupted by Chilton and the police who escort her from the building."
      },
      "tp5": {
        "index": 26,
        "pct": 0.929,
        "text": "Some time later at her FBI Academy graduation party, Starling receives a phone call from Lecter, who is at an airport in Bimini."
      }
    }
  },
  {
    "movie": "Slumdog Millionaire",
    "totalSentences": 45,
    "turningPoints": {
      "tp1": {
        "index": 10,
        "pct": 0.222,
        "text": "As they flee the riot, they run into a child version of the God Rama, Salim and Jamal then meet Latika, another child from their slum."
      },
      "tp2": {
        "index": 19,
        "pct": 0.422,
        "text": "Arriving at their hotel room, Salim orders Jamal to leave him and Latika alone."
      },
      "tp3": {
        "index": 25,
        "pct": 0.556,
        "text": "While Jamal professes his love for her, Latika asks him to forget about her."
      },
      "tp4": {
        "index": 30,
        "pct": 0.667,
        "text": "He makes it to the final question, despite the hostile attitude of the show's host, Prem Kumar (Anil Kapoor), and becomes a wonder across India."
      },
      "tp5": {
        "index": 38,
        "pct": 0.844,
        "text": "Jamal uses his Phone-A-Friend lifeline to call Salim's cell, as it is the only phone number he knows."
      }
    }
  },
  {
    "movie": "Panic Room",
    "totalSentences": 32,
    "turningPoints": {
      "tp1": {
        "index": 3,
        "pct": 0.094,
        "text": "The \"panic room\" is protected by concrete and steel on all sides, a thick steel door, and an extensive security system with multiple surveillance cameras, a public announcement system, and a separate phone line."
      },
      "tp2": {
        "index": 7,
        "pct": 0.219,
        "text": "As they begin the robbery, Meg wakes up and happens to see the intruders on the video monitors in the panic room."
      },
      "tp3": {
        "index": 16,
        "pct": 0.5,
        "text": "Stephen arrives at the home and is taken hostage by Burnham and Raoul—who severely beats him."
      },
      "tp4": {
        "index": 26,
        "pct": 0.813,
        "text": "Having earlier received a call from Stephen, two policemen arrive, which prompts Raoul to threaten Sarah's life."
      },
      "tp5": {
        "index": 29,
        "pct": 0.906,
        "text": "As the robbers attempt to leave, using Sarah as a hostage, Meg hits Raoul with a sledgehammer and Burnham flees."
      }
    }
  },
  {
    "movie": "The Shining (film)",
    "totalSentences": 43,
    "turningPoints": {
      "tp1": {
        "index": 2,
        "pct": 0.047,
        "text": "The hotel itself is built on the site of a Native American burial ground and becomes completely snowed in during the long winters."
      },
      "tp2": {
        "index": 9,
        "pct": 0.209,
        "text": "Danny asks if there is anything to be afraid of in the hotel, particularly Room 237."
      },
      "tp3": {
        "index": 16,
        "pct": 0.372,
        "text": "Later, Wendy finds Jack, asleep at his typewriter, screaming while in the midst of a horrifying nightmare."
      },
      "tp4": {
        "index": 32,
        "pct": 0.744,
        "text": "When Wendy sees this in the bedroom mirror, the letters spell out \"MURDƎЯ\"."
      },
      "tp5": {
        "index": 41,
        "pct": 0.953,
        "text": "Meanwhile, Danny walks backwards in his own tracks and leaps behind a corner, covering his tracks with snow to mislead Jack, who is following his footprints."
      }
    }
  },
  {
    "movie": "The Truman Show",
    "totalSentences": 30,
    "turningPoints": {
      "tp1": {
        "index": 9,
        "pct": 0.3,
        "text": "During the 30th year of the show, Truman notices certain aspects of his near-perfect world that seem out of place."
      },
      "tp2": {
        "index": 14,
        "pct": 0.467,
        "text": "Meryl grows increasingly stressed by the pressure of perpetuating the deception, and their marriage unravels in the face of Truman's increasing skepticism and attendant hostility towards her."
      },
      "tp3": {
        "index": 17,
        "pct": 0.567,
        "text": "However, he only provides a temporary respite: Truman soon becomes isolated and begins staying alone in his basement after Meryl leaves him."
      },
      "tp4": {
        "index": 21,
        "pct": 0.7,
        "text": "They find that Truman has overcome his fear of the water and has sailed away from the town in a small boat named Santa Maria."
      },
      "tp5": {
        "index": 26,
        "pct": 0.867,
        "text": "As he contemplates leaving his world, Christof speaks directly to Truman via a powerful sound system, trying to persuade him to stay and arguing that there is no more truth in the real world than there is in his own, artificial world."
      }
    }
  },
  {
    "movie": "Titanic (1997 film)",
    "totalSentences": 42,
    "turningPoints": {
      "tp1": {
        "index": 6,
        "pct": 0.143,
        "text": "Ruth emphasizes that Rose's marriage will resolve the DeWitt Bukaters' financial problems."
      },
      "tp2": {
        "index": 12,
        "pct": 0.286,
        "text": "Following dinner, Rose secretly joins Jack at a party in steerage."
      },
      "tp3": {
        "index": 16,
        "pct": 0.381,
        "text": "They evade Cal's bodyguard and have sex in an automobile in the ship's cargo hold."
      },
      "tp4": {
        "index": 24,
        "pct": 0.571,
        "text": "They return to the top deck, where Cal and Jack encourage her to board a lifeboat; Cal claims he can get himself and Jack off safely."
      },
      "tp5": {
        "index": 34,
        "pct": 0.81,
        "text": "Holding the edge, Jack assures Rose she will die an old woman, warm in her bed."
      }
    }
  }
] as TripodMovieExample[];

// ---------------------------------------------------------------------------
// Save the Cat Beat → TRIPOD Turning Point Mapping
// ---------------------------------------------------------------------------

export const BEAT_TO_TP_MAP: Record<string, TurningPointKey | null> = {
  'Opening Image': null,
  'Theme Stated': null,
  'Set-Up': null,
  'Catalyst': 'tp1',
  'Debate': null,
  'Break into Two': 'tp2',
  'B Story': null,
  'Fun and Games': null,
  'Midpoint': 'tp3',
  'Bad Guys Close In': null,
  'All Is Lost': null,
  'Dark Night of the Soul': null,
  'Break into Three': 'tp4',
  'Finale': 'tp5',
  'Final Image': null,
};
