// ---------------------------------------------------------------------------
// TRIPOD Vector Store (GENERATED — do not edit manually)
// ---------------------------------------------------------------------------
//
// Generated by: scripts/build-tripod-vectors.ts
// Source: TRIPOD dataset
// Total chunks: 3441
//
// Run `npx tsx scripts/build-tripod-vectors.ts` to regenerate.
// ---------------------------------------------------------------------------

import type { TurningPointKey } from './types';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ChunkType = 'turning_point' | 'scene' | 'dialogue_excerpt';

export interface VectorChunk {
  id: string;
  type: ChunkType;
  movie: string;
  text: string;
  /** Quantized embedding (int8, multiply by 1/127 to restore floats) */
  embedding: number[];
  metadata: {
    turningPoint?: TurningPointKey;
    label?: string;
    position?: number;
    sceneIndex?: number;
    heading?: string;
    character?: string;
    genre?: string;
    dialogueDensity?: number;
  };
}

// ---------------------------------------------------------------------------
// Vector Store Data
// ---------------------------------------------------------------------------

// The vector data is stored in a separate JSON file to avoid TypeScript
// complexity issues with large literal types. Import the data at runtime.
import vectorData from './vector-data.json';

export const VECTOR_CHUNKS: VectorChunk[] = vectorData.chunks;
export const CHUNK_INDEX: Record<string, number> = vectorData.index;

// ---------------------------------------------------------------------------
// Statistics
// ---------------------------------------------------------------------------

export const VECTOR_STORE_STATS = {
  totalChunks: 3441,
  turningPointChunks: 524,
  sceneChunks: 1842,
  dialogueChunks: 1075,
  embeddingDimension: 1536,
  generatedAt: '2026-01-31T03:50:40.207Z',
};
